프로젝트 API 문서 작업을 위해 Controller 추가, RestDocs 테스트 개발
donggi-lee-bit/comma pull request #24
Opened 2023-01-05 13:05 UTC by donggi-lee-bit

### 📝 구현 내용

- 회고 생성, 수정, 조회, 삭제 컨트롤러와 RestDocs 테스트 추가
- 검색 조건으로 회고 글 조회 컨트롤러, RestDocs 테스트 추가
- 댓글 생성, 수정, 삭제 컨트롤러, RestDocs 테스트 추가

좋아요 기능도 추가하려고 했었지만 로그인도 같이 필요할 것 같아 일단 여기까지 작업한 내용 보냅니다!

잘 부탁드리겠습니다. 🫡😆

<br><br>

### 💡 참고 자료

<img width="588" alt="Screen Shot 2023-01-05 at 10 05 07 PM" src="https://user-images.githubusercontent.com/73376468/210786739-e7deb5b6-012e-42cb-93c8-69c1471a19fd.png">

2023-01-05 14:35 UTC, ku-kim requested changes
RestDocs 결과물도 추가 부탁드려요.

2023-01-18 15:26 UTC, donggi-lee-bit commented
> RestDocs 결과물도 추가 부탁드려요.

RestDocs 설정에 에러 해결을 하느라 시간이 오래 걸렸습니다 😥
RestDocs 결과물 추가했습니다!

2023-01-18 15:28 UTC, donggi-lee-bit commented
![screencapture-localhost-63342-commaserver-commaserver-main-static-docs-index-html-2023-01-19-00_27_41](https://user-images.githubusercontent.com/73376468/213213164-2633e06d-4010-492d-8c92-9f76f7d8dc12.png)
![screencapture-localhost-63342-commaserver-commaserver-main-static-docs-index-html-2023-01-19-00_27_41-2](https://user-images.githubusercontent.com/73376468/213213193-9a461e99-9ca1-43b1-bd90-f1cb6016fe3d.png)

2023-01-19 05:37 UTC, donggi-lee-bit commented
디스코드 웹후크 테스트 메세지입니다.

2023-01-19 05:42 UTC, donggi-lee-bit commented
스압 주의.

2023-01-19 10:29 UTC, ku-kim approved these changes
RestDocs 설정도 복잡한데 AsciiDoc 문법까지 익히기 어려웠을텐데 고생 많으셨어요 동기!
swagger vs RestDocs 는 정말 어려운거 같습니다. ㅎㅎ

p.s. api 문서 커스텀을 하라는 것은 아니니 오해하지 마시기 바라며

2023-01-19 10:29 UTC, ku-kim commented on src/test/java/commaproject/be/commaserver/controller/CommaSearchControllerTest.java
> +                        fieldWithPath("data[].comments[].content").type(JsonFieldType.STRING).description("댓글 내용")
+a) RestDocs를 커스텀해서 반복되는 부분을 메서드로 분리해서 작업할 수 있는데요. 현재 급한 것은 아니고 시간도 오래걸리니 참고정도만 하면 좋을 거 같아요.

2023-01-19 10:29 UTC, ku-kim commented on src/docs/asciidoc/index.adoc
> +include::{snippets}/comma-all-get/http-response.adoc[]
p3) 해당 api가 어떤 메서드, uri로 접근하고 간단히 어떤 내용을 하고 있는지 추가해주면 보기 더 좋을 거 같아요.!  
+a) 여유로울 때 문서 커스텀..? ㅎㅎ  

제가 했었던 예 입니다.

- https://api.jjikmuk.com/docs/index.html (23.04 월에 사라질 예정)

![image](https://user-images.githubusercontent.com/57086195/213417500-749fd250-9246-4216-8935-97da555c3369.png)

2023-01-19 10:29 UTC, ku-kim commented on src/main/java/commaproject/be/commaserver/service/dto/SearchConditionRequest.java
> +@EqualsAndHashCode
Q) EqualsAndHashCode 어노테이션을 사용한 특별한 이유가 있을까요?

2023-01-19 10:29 UTC, ku-kim commented on src/main/java/commaproject/be/commaserver/service/dto/SearchConditionRequest.java
> +@AllArgsConstructor
Q) 단순 생성자 대신 AllArgsConstructor 사용한 특별한 이유가 있을까요?

2023-01-20 14:39 UTC, donggi-lee-bit commented on src/test/java/commaproject/be/commaserver/controller/CommaSearchControllerTest.java
> +                        fieldWithPath("data[].comments[].content").type(JsonFieldType.STRING).description("댓글 내용")
개선하는 작업을 진행할 때 반복되는 부분을 제거해보도록 하겠습니다! 감사합니다 🙇‍♂️

2023-01-20 14:44 UTC, donggi-lee-bit commented on src/docs/asciidoc/index.adoc
> +include::{snippets}/comma-all-get/http-response.adoc[]
어떤 `uri` 로 접근하고 있는지, 어떤 작업이 이루어지에 대한 글을 작성해주는게 문서를 보는 입장에서 훨씬 편하겠네요!! 문서 커스텀 작업을 한 번 해야할 것 같네요. ㅎㅎ 감사합니다!

2023-01-20 15:35 UTC, donggi-lee-bit commented on src/main/java/commaproject/be/commaserver/service/dto/SearchConditionRequest.java
> +@EqualsAndHashCode
컨트롤러 테스트에서 Service를 `mocking` 할 때 파라미터로 해당 `dto`를 넣어주고 있습니다. 
이 때 테스트가 기대한 것처럼 실행하지 않았는데 `MockMvc`에 전달한 `dto`와 `when(service.method(searchConditionRequest))` 의 `dto` 가 다르다고 판단했기 때문입니다.

`dto` 클래스 객체의 동일성을 비교할 때 `객체의 값`을 비교하는 것이 아닌 `주소값`을 비교하도록 동작하고 있었습니다. 그렇다면 `주소값`을 비교했을 때 달랐던 이유는 `DTO` 객체를 JSON 형태의 문자열로 직렬화하여 컨트롤러에서 요청을 보내면 해당 컨트롤러는 요청의 body를 읽어 다시 역직렬화하여 새로운 `DTO` 객체를 만들게 됩니다.

이 과정에서 만들어진 `DTO` 객체는 새로운 주소값을 갖기 때문에 `주소값 비교`를 했을 때 다르다고 판단되어 테스트가 실패하게 되었습니다.

그렇게하여 사용하게 된 것이 `EqualsAndHashCode` 어노테이션을 사용하게 되었습니다. 이 어노테이션을 사용함으로써 `equals` 메서드와 `hashcode` 메서드를 오버라이딩 하여 주소값이 아닌 필드값을 비교할 수 있었고 테스트가 기대한 것처럼 동작할 수 있었습니다.

2023-01-20 18:58 UTC, donggi-lee-bit commented on src/main/java/commaproject/be/commaserver/service/dto/SearchConditionRequest.java
> +@AllArgsConstructor
단순 생성자 대신 `AllArgsConstructor` 를 사용한 건 단순 롬복의 편의성으로 사용하였는데 사용할 때 고려해야할 게 있을까요?? 🤔

2023-01-20 18:59 UTC, merged

2023-01-21 07:11 UTC, ku-kim commented on src/main/java/commaproject/be/commaserver/service/dto/SearchConditionRequest.java
> +@EqualsAndHashCode
Q) 현재 코드에서 MockMvc 를 사용한 andExpect() 테스트가 현재 status().isOk() 밖에 안보이는데 객체를 비교할 필요가 있었나해서요. 테스트에서 필요하더라도 객체 전체를 비교한다기 보다는 값을 꺼내서 비교하는 방법도 있지 않나요?

Q) AllArgsConstructor와 EqualsAndHashCode 사용한 이유를 물어본 것은 롬북 사용시 문제점을 인지하고 있는지 물어본거였어요 ㅎㅎ

2023-01-21 07:12 UTC, ku-kim commented on src/main/java/commaproject/be/commaserver/service/dto/SearchConditionRequest.java
> +@AllArgsConstructor
개인적으로 AllArgsConstructor는 사용하지 않는 편이라서요.
필드들의 순서가 바뀌거나 요구사항 변경으로 필드 수정, 추가되면 대처가 어려운 이유 때문이에요.

ref : https://kwonnam.pe.kr/wiki/java/lombok/pitfall#%EB%AC%B4%EB%B6%84%EB%B3%84%ED%95%9C_equalsandhashcode_%EC%82%AC%EC%9A%A9_%EC%9E%90%EC%A0%9C

2023-01-21 07:15 UTC, ku-kim commented on src/main/java/commaproject/be/commaserver/service/dto/CommaRequest.java
> +    private Long userId;
title, content, username 순서가 바뀐다면 AllArgsConstructor로 생성된 생성자의 컴파일 에러도 잡을 수 없을 거 같아요.

2023-01-21 08:31 UTC, donggi-lee-bit commented on src/main/java/commaproject/be/commaserver/service/dto/SearchConditionRequest.java
> +@AllArgsConstructor
이전에도 읽었던 글인데 정작 개발할 때 경각심 없이 AllArgsConstructor 어노테이션을 사용하고 있었네요 😅 
말씀하신 것처럼 개발이 진행되면서 필드의 순서가 바뀌거나 수정, 추가 되었을 때 에러의 원인이 될 수 있을 것 같다는 생각이 듭니다!
어노테이션 사용보다 생성자를 직접 만들어 사용하는걸로 바꿔보겠습니다!

2023-01-21 08:39 UTC, donggi-lee-bit commented on src/main/java/commaproject/be/commaserver/service/dto/SearchConditionRequest.java
> +@EqualsAndHashCode
AllArgsConstructor와 EqualsAndHashCode 사용시 문제점을 인지하지 않고 사용해서 핀트와 맞지 않는 답변을 드리게 됐네요 😅
`EqualsAndHashCode` 어노테이션을 사용하고 있을 때 필드 값이 변경되면 기존에 저장된 객체의 HashCode가 변경되면서 기존 객체를 찾을 수 없다는 문제를 알게 되었습니다!

이번 케이스에서도 사용하지 않는 것이 좋아보이네요 🤔

SearchConditionRequest 클래스를 현재 Service의 파라미터로 넣어주고 있습니다.

```java
```

2023-01-21 11:24 UTC, ku-kim commented on src/main/java/commaproject/be/commaserver/service/dto/SearchConditionRequest.java
> +@EqualsAndHashCode
Request 객체는 특별한 이유가 없다면 불변 객체로 사용되니 EqualsAndHashCode 써도 괜찮아보이긴해요. ㅎㅎ
+a) Java 17 쓴다면 Record 키워드 쓰면 좀 더 편하게 관리할 수 있더라구요