Comma 도메인, CRUD 개발
donggi-lee-bit/comma pull request #27
Opened 2023-01-26 15:25 UTC by donggi-lee-bit

### ❗️ 이슈 번호

Closes #25 

<br><br>

### 📝 구현 내용

- Comma CRUD 개발
- 서비스 계층 단위 테스트
- 도메인 저장, 수정 필드를 저장하기 위해 BaseEntity 추가
- EnableJpaAuditing 어노테이션을 추가하기 위해 JpaConfig 추가

**리뷰 반영 사항**
- [x] AllArgsConstructor 어노테이션 사용 대신 생성자 만들어서 사용

프로젝트를 하면서 얕게 알고 있던 지식을 더 공부하고, 새로운 것들을 익히게 되면서 예상한 시간보다 개발 시간이 오래 걸리고 있습니다. 그 과정에서 트레이드오프를 고민해보는 것이 재밌기도 합니다. 이번에는 레파지토리를 모킹하여 서비스 레이어 단위 테스트를 하면서 독립적인(?) 서비스 계층을 테스트하고 싶었으나 테스트를 짜면서 의도한대로 잘 되고 있는가 하는 의구심이 들었습니다.

통합테스트와 서비스 계층 단위 테스트에 대해서 생각해보았는데 개인적으로 [이 글](https://tecoble.techcourse.co.kr/post/2022-10-15-test-code-optimization/)의 통합테스트 부분을 읽고 객체 간의 협력은 통합테스트로 테스트하고 서비스 계층 단위테스트도 따로 해주는 게 맞는건가? 합니다. 하지만 아직까지 테스트를 짜본 경험도 많지 않고 모르는 것 투성이니 리뷰어님의 의견도 듣고 계속 공부해가며 올바른 선택을 할 수 있도록 노력하겠습니다~😁

### 궁금한 점

서비스 계층의 단위 테스트 중 `Comma`를 soft delete 하는 테스트가 실패한채 있습니다. 실패하는 이유를 생각해본 것은 레파지토리를 모킹하였기 때문에 데이터를 저장해도 JPA가 id를 생성해주지 않는 것인가 합니다. 그래서 findById의 파라미터로 `Comma`가 가지고 있는 `id`로 데이터를 조회하려할 때 조회가 되지 않는다고 생각하고 있습니다.

이런 상황에서 어떻게 서비스 계층에서 soft delete한 것에 대한 테스트를 진행해야할지 알고 싶습니다.

<br><br>

### 💡 참고 자료

<img width="671" alt="Screen Shot 2023-01-26 at 11 49 34 PM" src="https://user-images.githubusercontent.com/73376468/214866892-c24300f4-e6b5-4fbc-bdeb-9672f7dc7c3b.png">

- 새로 추가된 테스트를 표시해두었습니다

2023-01-27 01:51 UTC, ku-kim requested changes
고생하셨어요.!
레이어 별 단위 테스트를 위해 mocking 하는 방식도 좋고 통합 테스트도 좋아요. 도전해봤다는 것에 따봉을 드립니다.

- 테스트 관련 질문은 리뷰에 남겨두었습니다.
- 테스트 코드에만 application.yml이 있고 운영 코드에는 없군요. 
  - Q) 현재 테스트에서 모두 mock 하고있어서 mysql context를 사용하고 있지 않는거같은데 넣은 특별한 이유가 있나요?
  - p3) Comma 도메인, CRUD 개발이라면 테스트 말고 spring 실행 환경에서도 사용하면 좋을 거 같아요. (application context 뜬 상황에서) 현재는 mock 테스트 환경에서만 작동하는 것으로 보이네요.

2023-01-27 01:51 UTC, ku-kim commented on src/test/java/commaproject/be/commaserver/service/CommaServiceTest.java
> +    }
mock 했기 때문에 save()메서드 호출시에만 저장됩니다.
따라서 자동으로 데이터가 저장되지 않습니다.

구현하신 remove()메서드는 아래와 같은데
```java
    public CommaResponse remove(Long commaId) {
        Comma findComma = commaRepository.findById(commaId)
            .orElseThrow(NoSuchElementException::new); // findById() 메서드에 대한 mock이 없기 때문에 null이 발생하고, 자연스럽게 NoSuch~ 테스트 실패가 아닌 익셉션이 발생했습니다.
        commaRepository.delete(findComma);
        return new CommaResponse(findComma.getId());
    }
```

여기서 검증하고자 하는 것이 delete 메서드가 1번 실행되었는가? 검증하는 것이라면 테스트 코드는 아래와 같은 예로 작성되어야 합니다.
```suggestion
    @Test
    @DisplayName("유효한 commaId로 회고를 조회하여 soft delete를 하면 테스트가 성공한다")
    void remove_comma() {
        // given
        Long userId = 1L;
        Comma comma = Comma.from("title1", "content1", "username", userId);
        when(commaRepository.findById(any())).thenReturn(Optional.of(comma));


        // when
        Long commaId = 1L;
        commaService.remove(commaId);

        // then
        verify(commaRepository, times(1)).delete(any());
    }

```

2023-01-27 01:51 UTC, ku-kim commented on src/main/java/commaproject/be/commaserver/service/CommaServiceImpl.java
> +    }
p3; 반복문을 stream으로 변경 가능해요

2023-01-27 01:51 UTC, ku-kim commented on src/main/java/commaproject/be/commaserver/service/CommaServiceImpl.java
> +            );
p3; 로직 단위로 개행으로 굽구분 지어주는 건 어떤가요?
```suggestion
        // user, like, comment 도메인 개발 예정
        Comma findComma = commaRepository.findById(commaId)
            .orElseThrow(NoSuchElementException::new);
        Long userId = 1L;
        int likeCount = 1;
        List<CommentDetailResponse> comments = new ArrayList<>();
        
        return new CommaDetailResponse(
            findComma.getId(),
            findComma.getTitle(),
            findComma.getContent(),
            findComma.getUsername(),
            userId,
            findComma.getCreatedAt(),
            likeCount,
            comments
            );
```

2023-01-27 01:51 UTC, ku-kim commented on src/main/java/commaproject/be/commaserver/service/CommaServiceImpl.java
> +    }
```suggestion
    @Override
    @Transactional
    public CommaResponse remove(Long commaId) {
        Comma findComma = commaRepository.findById(commaId)
            .orElseThrow(NoSuchElementException::new);
            
        commaRepository.delete(findComma);
        
        return new CommaResponse(findComma.getId());
    }
```

2023-01-27 04:34 UTC, donggi-lee-bit commented on src/test/java/commaproject/be/commaserver/service/CommaServiceTest.java
> +    }
`mock`하면 데이터를 저장하고 저장한 데이터를 호출할 수 없군요 ㅎㅎ;; 감사합니다!!

2023-01-27 04:35 UTC, donggi-lee-bit commented on src/main/java/commaproject/be/commaserver/service/CommaServiceImpl.java
> +            );
개행을 로직 단위를 구분해주는 것 좋네요!! 확실히 더 읽기 편하다고 생각됩니다 ㅎㅎ 감사합니다!

2023-01-27 04:41 UTC, donggi-lee-bit commented
> 

테스트를 `mock`으로 하고 있어서 test 환경에 있는 `application.yml` 설정은 필요가 없다는 걸 인지하지 못하고 있었습니다.. 😅
테스트 환경에서 테스트 컨테이너를 통해 DB 연결을 하고자 했었지만 변경하게 되었고, 로컬에서 DB와 연결해야겠다~ 생각하곤 실제로는 `mock` 으로 테스트했네요 😅

말씀하신 것처럼 현재 테스트에서만 mysql 연결을 시도하고 있어 spring 실행 환경에서 사용하도록 변경하겠습니다!

2023-01-27 06:22 UTC, ku-kim commented on src/test/java/commaproject/be/commaserver/service/CommaServiceTest.java
> +    }
mock은 말그대로 mock 이니까요.
JPA나 레포 구현체는 작동하지 않죠

2023-01-27 06:23 UTC, ku-kim commented
수정 후 PR 주시면 빠르게 봐드릴게요~

2023-01-27 08:17 UTC, donggi-lee-bit commented on src/test/java/commaproject/be/commaserver/service/CommaServiceTest.java
> +    }
JPA가 해주는 것들로 테스트하기 위해선 통합테스트가 필요하겠군요 🤔

2023-01-27 09:15 UTC, donggi-lee-bit commented
> 수정 후 PR 주시면 빠르게 봐드릴게요~

수정한 내용 추가하였습니다!!

2023-01-28 05:21 UTC, ku-kim approved these changes
다음 PR에서 운영에 필요한 설정 추가되면 좋을거같네요.
고생하셨습니다.!

2023-01-28 05:23 UTC, ku-kim commented on src/test/java/commaproject/be/commaserver/service/CommaServiceTest.java
> +    }
JPA만을 테스트하기 원한다면 테스트 컨텍스트 범위를 줄이기 위해 `@DataJpaTest` 사용할 수 있어요.

2023-01-28 10:56 UTC, donggi-lee-bit commented on src/test/java/commaproject/be/commaserver/service/CommaServiceTest.java
> +        assertThat(removeComma).isNotNull();
특별한 이유라기보다 아직 `verify` 사용이 익숙치 않아 빠뜨리게 됐습니다! 다시 추가해놓겠습니다 😆

2023-01-28 10:59 UTC, donggi-lee-bit commented on src/main/java/commaproject/be/commaserver/service/CommaServiceImpl.java
> +            .collect(Collectors.toUnmodifiableList());
java 17에 대한 팁 매번 감사합니다!!

2023-01-28 11:01 UTC, donggi-lee-bit commented on src/test/java/commaproject/be/commaserver/service/CommaServiceTest.java
> +    }
통합테스트를 할 때 `@DataJpaTest`로 테스트 컨텍스트 범위 조정!!! 감사합니다 ㅎㅎ

2023-01-28 11:07 UTC, merged