좋아요 기능 구현
donggi-lee-bit/comma pull request #38
Opened 2023-02-14 10:03 UTC by donggi-lee-bit

### ❗️ 이슈 번호

Closes #37 

<br><br>

### 📝 구현 내용

** 좋아요 기능 구현**
- [x] 좋아요 요청 기능 개발
- [x] 좋아요 취소 요청 기능 개발
- [x] 컨트롤러, 서비스 테스트

**리뷰 반영**
- [x] 게시글 엔티티 soft delete 로직 수정
<br><br>

### 💡 참고 자료

<img width="731" alt="Screen Shot 2023-02-14 at 6 54 17 PM" src="https://user-images.githubusercontent.com/73376468/218701275-305b5d4c-4a42-4384-9729-9b46e397ad18.png">

2023-02-17 01:26 UTC, ku-kim requested changes
고생 많았어요 동기!
Like 도메인에 대한 ElementCollections vs Entity 에 대해 좀 더 이야기 나눠보면 좋을 거 같아요.! 

p.s. 리뷰가 늦어 미안합니다. 🥹

2023-02-17 01:26 UTC, ku-kim commented on src/main/java/commaproject/be/commaserver/domain/comma/Comma.java
> +
q) 특별히 Set을 활용한 ElementCollection을 사용한 이유가 있나요?

2023-02-17 01:26 UTC, ku-kim commented on src/main/java/commaproject/be/commaserver/service/PostLikeServiceImpl.java
> +}
p2; 현재 ElementCollections를 활용해 comma와 user에서 like 모두를 저장하고 있잖아요? 
따라서, 두 곳에서 검증과 동일한 데이터 관리해야하는 단점이 있어보여요.
ElementCollections가 아닌 Like라는 엔티티를 만든다면 ElementCollections 조회를 위해 comma나 user를 모두 조회하지 않고, 특정 commaId의 Like를 CUD할 수 있고, 만약 특정 유저의(userId)에 대한 Like도 한 번에 조회할 수 있는 장점이 있다고 생각해요. 

+a) 만약 User의 특정 Comma에 대한 Like 히스토리 정보가 별도로 필요하고 RDB에서 저장하기로 약속이 되어있다면 Like 엔티티를 User_Like_History와 같은 엔티티 두 개를 구분 지으면 히스토리까지 관리가 가능하다고 생각합니다.

동기는 어떻게 생각하시나요? ㅎㅎ 위 리뷰의 연장선입니다.

2023-02-17 01:26 UTC, ku-kim commented on src/test/java/commaproject/be/commaserver/service/PostLikeServiceTest.java
> +    }
깰꿈! 🥳

2023-02-18 06:55 UTC, donggi-lee-bit commented on src/main/java/commaproject/be/commaserver/domain/comma/Comma.java
> +
`Set` 자료구조를 사용한 건 `특정 유저가 특정 회고 게시글의 좋아요를 눌렀을때 이미 누른 게시글이라면 예외를 발생시킨다` 를 구현하기 위해 특정 값을 포함하고 있는지 확인하는 작업이 필요했습니다.

그때 특정 값을 포함하고 있는지 확인하는 `contains()` 메서드의 시간복잡도가 O(1) 인 Set 자료구조를 사용하게 됐습니다!

2023-02-18 07:38 UTC, donggi-lee-bit commented on src/main/java/commaproject/be/commaserver/service/PostLikeServiceImpl.java
> +}
Like를 `ElementCollection` 을 이용해 관리하면 생기는 단점이 여럿 있군요 😅
Like 같은 경우엔 `Entity` 로 관리하는게 맞겠네요!! 
히스토리도 개발해보고 싶었는데 좋은 방향을 제시해주셔서 감사합니다!

2023-02-18 12:50 UTC, ku-kim commented on src/main/java/commaproject/be/commaserver/domain/comma/Comma.java
> +
검색이 빠르군요! 👍

2023-02-18 12:52 UTC, ku-kim commented on src/main/java/commaproject/be/commaserver/service/PostLikeServiceImpl.java
> +}
히스토리 관리는 요구사항에 따라 방법이 다양할 거 같아요. 잘 정해봐야겠네요.!

2023-02-18 12:54 UTC, ku-kim commented on src/main/java/commaproject/be/commaserver/service/PostLikeServiceImpl.java
> +}
엔티티가 아닌 ElementCollection 구현으로 그대로 가거나 다음 PR에서 적용한다면 머지해도 될 거 같아요.
일단 approve 할게요.

2023-02-18 12:54 UTC, ku-kim approved these changes

2023-02-20 07:14 UTC, ku-kim approved these changes
Like 엔티티로 구분했군요. 고생하셨습니다 👍

2023-02-20 07:14 UTC, ku-kim commented on src/main/java/commaproject/be/commaserver/service/PostLikeServiceImpl.java
> +        like.clickPostLike(true);                      // 6. likeStatus 가 false 면 true 로 상태를 변경해준다
p3; 주석 제거

2023-02-20 09:22 UTC, donggi-lee-bit commented on src/main/java/commaproject/be/commaserver/service/PostLikeServiceImpl.java
> +    }
`Optional` 의 `orElseGet()` 메서드를 이용하여 한 번만 조회하도록 변경해보겠습니다!

2023-02-20 09:25 UTC, donggi-lee-bit commented on src/main/java/commaproject/be/commaserver/domain/like/Like.java
> +    }
`Like.update()` 가 의미 전달에 좋아보이네요 ㅎㅎ
아래에 지워진 피드백은 예외처리와 상관없이 네이밍이 와닿지 않아서 지워진걸까요?!

2023-02-20 09:36 UTC, donggi-lee-bit commented on src/main/java/commaproject/be/commaserver/service/CommaServiceImpl.java
>          }
회고 게시글을 수정할 때 해당 게시글을 작성한 사용자임을 확인하는 작업은 Comma 도메인의 책임

Comma 도메인에게 책임을 주는 게 더 좋아보이네요(?) 맞아보이네요?!
객체지향 공부 좀 더 해보겠습니다..ㅎㅎ

2023-02-20 09:49 UTC, merged