엔티티 연관관계 설정 및 회고 게시글 검색 조회 기능 개발
donggi-lee-bit/comma pull request #42
Opened 2023-02-22 11:54 UTC by donggi-lee-bit

### ❗️ 이슈 번호

Closes #39 
Closes #41  

<br><br>

### 📝 구현 내용

**개발**
- [x] Comma, Like, User 엔티티 연관관계 매핑
- [x] QueryDsl 의존성, 설정 추가
- [x] 회고 게시글 검색 조회 기능 개발
  - [x] 특정 날짜에 작성된 회고 게시글 조회
  - [x] 특정 유저가 작성한 회고 게시글 조회
  - [x] 특정 날짜에 특정 유저가 작성한 회고 게시글 조회

**변경**
- [x] 상수로 넣어주고 있던 댓글 데이터를 만들어진 로직으로 변경
- [x] 실행되는 query 를 확인할 수 있는 show_sql 옵션 오타 수정 : show-sql -> show_sql

<br><br>

### 💡 참고 자료

<img width="617" alt="Screen Shot 2023-02-22 at 8 38 03 PM" src="https://user-images.githubusercontent.com/73376468/220609447-86ca7106-42de-4b44-a5d8-2dcc2640c875.png">

2023-02-22 11:57 UTC, donggi-lee-bit commented on src/main/java/commaproject/be/commaserver/common/config/QueryDslConfig.java
> +}
QueryDsl 의 동적 쿼리를 사용하기 위해 `JPAQueryFactory` 를 `bean` 등록해주기 위한 Config 작업입니다.

2023-02-22 23:25 UTC, ku-kim commented on src/main/java/commaproject/be/commaserver/domain/comma/Comma.java
> +
Goo

2023-02-22 23:52 UTC, ku-kim requested changes
연관관계, QueryDSL, 테스트까지 고생많으셨어요 동기!
이제 테스트 작성이 익숙해져 보이네요.!
더 나아가 현재 요구사항이 변경되면 테스트 코드 영역의 많은 코드까지 변경을 겪으실텐데요.
어떻게 느끼셨는지도 궁금하네요. ㅎㅎ

2023-02-22 23:52 UTC, ku-kim commented on src/main/java/commaproject/be/commaserver/domain/comma/Comma.java
> +    private User user;
Good

2023-02-22 23:52 UTC, ku-kim commented on src/main/java/commaproject/be/commaserver/repository/CommaSearchRepository.java
> +}
검색용 인터페이스를 추가해주었군요!

2023-02-22 23:52 UTC, ku-kim commented on src/main/java/commaproject/be/commaserver/repository/CommaSearchRepositoryImpl.java
> +}
QueryDSL을 적용했군요.! 고생 하셨네요 ㅎㅎ
Q) 혹시 QueryDSL를 도입한 이유가 있을까요? 사용했을 때 장단점을 알고싶어요.!

2023-02-22 23:52 UTC, ku-kim commented on src/main/java/commaproject/be/commaserver/service/CommaSearchServiceImpl.java
> +    private final CommaRepository commaRepository;
Q) CommaSearchRepository가 아닌 CommaRepository를 사용한 이유가 있나요?

2023-02-22 23:52 UTC, ku-kim commented on src/main/java/commaproject/be/commaserver/service/CommaSearchServiceImpl.java
> +        LocalDateTime endDate = startDate.plusDays(1);
현재날짜 기준으로 다음날까지 검색되는걸까요? 
p2; 가독성과 의미를 주기 위해 plusDays(1)의 1을 상수로 관리해주는게 좋을 거 같아요.!

2023-02-22 23:52 UTC, ku-kim commented on src/main/java/commaproject/be/commaserver/service/CommaServiceImpl.java
> +            .orElseThrow(NotFoundCommentException::new);
p1; findAll() 메서드의 리턴값이 Optional의 Null이 발생하나요? JPA에서 리스트 반환이 옵셔널 리턴이 되는지 확인이 필요합니다.
Optional<List<T>> 형식으로 쓰게 되면 Optional 제네릭 안에 있는 List<T> 는 리스트가 비어도 빈 리스트를 반환하지 null이 절대로 될 수 없어 보이네요.

2023-02-22 23:52 UTC, ku-kim commented on src/main/java/commaproject/be/commaserver/service/dto/CommaSearchConditionRequest.java
> +    private final String username;
p3; 요청받은 날짜로부터 다음날 까지 검색한다면 dto나 서비스 네이밍이 좀 더 디테일해야하면 좋을 거 같아요.

2023-02-22 23:52 UTC, ku-kim commented on src/test/java/commaproject/be/commaserver/integration/CommaSearchIntegrationTest.java
> +}
네, 말씀하신것처럼 예외/엣지값 e.g. 데이터 없는 경우에 대한 테스트 검증이 필요해요.!
개인적으로 조회 부분까지 테스트하기 시간이 발생하니 어려울 수 있다고 생각하지만, 여유가있다면 체크해보는것도 좋네요.
하지만 조회 부분 요구사항이 자주 변경된다면 테스트도 그와 맞게 깨지기 때문에 적절히 선택이 필요하다고 생각합니다.

---

현재 게시글 List 빈값에 대해 테스트하고 있지 않아 JPA의 Optional<List<T>> 의 문제를 확인하지 못한 문제가 있었네요.!

2023-02-23 00:01 UTC, ku-kim commented on src/main/java/commaproject/be/commaserver/repository/CommaSearchRepositoryImpl.java
> +    }
p3; 이 메서드만 `@Override`가 빠져있네요.!

2023-02-23 01:34 UTC, donggi-lee-bit commented on src/main/java/commaproject/be/commaserver/repository/CommaSearchRepositoryImpl.java
> +}
QueryDSL의 

`장점`
- JPQL은 문자로 쿼리를 작성하기 때문에 오타나 문법적인 오류로 인한 에러가 발생할 수 있습니다. QueryDSL은 문자가 아닌 `코드`로 쿼리로 코드를 작성하기 때문에 컴파일 시점에 문법 오류를 확인할 수 있습니다
- 자바 코드로 쿼리를 작성하기에, 쿼리를 작성하고 관리하는데 필요한 작업이 줄어들어 `유지보수`에도 용이합니다

`단점`
- QueryDSL을 처음 사용하기 때문에 학습 곡선이 있습니다. 간단하게 의존성 하나만 추가해주는 게 아닌 gradle version에 맞춰 문법에 맞게 설정을 해주어야 합니다. 또한 Q 클래스 등 QueryDSL을 사용하기 위해서는 학습 해야할 것들이 있습니다
- 또한 SQL의 모든 기능을 지원하지 않아 그럴 땐 직접 쿼리를 작성해줘야 합니다

`작동 방식`
1. **`@Entity` 어노테이션이 붙은 클래스로 `Q클래스` 생성**

2. **QueryDSL을 사용하여 SQL 쿼리 작성**
생성된 Q클래스로 SQL 쿼리를 작성할 수 있게 됩니다.
`JPAQueryFactory`를 사용하여 SQL 쿼리를 생성하고 실행합니다

3. **ORM 프레임워크와 연동하여 SQL 쿼리 실행**
QueryDSL은 JPA, Hibernate, MyBatis 등 ORM 프레임워크와 연동하여 사용할 수 있습니다.
저의 경우 JPA를 사용하고 있기 때문에 `EntityManager`를 통해 QueryDSL을 사용하여 생성한 SQL 쿼리를 실행합니다.


현재 작성한 쿼리는 간단한 정도의 쿼리이기 때문에 JPQL만으로 충분할 수 있었습니다.
하지만 QueryDSL을 사용함으로서 가질 수 있는 타입 안정성과 유지 보수적인 부분에 이점이 있어 사용하게 되었습니다.
추가로 특정 기한 내에 좋아요가 높은 순서의 게시글 조회 등 다양한 조건으로 조회를 해보고자 합니다!

2023-02-23 15:33 UTC, donggi-lee-bit commented on src/main/java/commaproject/be/commaserver/service/CommaSearchServiceImpl.java
> +    private final CommaRepository commaRepository;
`검색을 통해 게시글을 가져온다` 는 가벼운 생각으로 사용했습니다 🥲

2023-02-23 15:47 UTC, donggi-lee-bit commented on src/main/java/commaproject/be/commaserver/service/CommaSearchServiceImpl.java
> +        LocalDateTime endDate = startDate.plusDays(1);
조건으로 들어온 날짜의 게시글을 조회하고자하는 의도입니다!
`eq` 메서드로는 의도한 것처럼 조회하고자 하는 날짜 데이터 조회가 안되는 문제가 있었습니다!
`between` 메서드를 이용해 현재 날짜로부터 다음날을 startDate, endDate로 조건을 줬을 때 의도한 것처럼 동작하는 걸 확인할 수 있었습니다!

혹시 다른 방법이 있을까요?

2023-02-23 16:03 UTC, donggi-lee-bit commented on src/main/java/commaproject/be/commaserver/service/CommaServiceImpl.java
> +            .orElseThrow(NotFoundCommentException::new);
이번 케이스도 테스트를 잘 작성했다면 잡아낼 수 있었는데..!! 라는 생각이 드네요 🥹

2023-02-23 16:07 UTC, donggi-lee-bit commented on src/test/java/commaproject/be/commaserver/integration/CommaSearchIntegrationTest.java
> +}
앞으론 좀 더 예외 테스트를 신경쓰면서 개발해보도록 하겠습니다 ❗️👯

2023-02-24 16:19 UTC, ku-kim approved these changes
다음 PR에서 성능 개선과 모니터링 기대할게요!

2023-02-24 16:21 UTC, merged