spring 애플리케이션 성능 점검을 위해 모니터링 툴 연결
donggi-lee-bit/comma pull request #47
Opened 2023-03-14 06:03 UTC by donggi-lee-bit

### ❗️ 이슈 번호

Closes #46 

<br><br>

### 📝 구현 내용

로컬 환경에서 spring 애플리케이션 성능 확인을 위해 모니터링 툴을 연결해보았습니다.

- `spring actuator` 로 spring 애플리케이션 모니터링
- `prometheus` 로 `metric` 수집
- `grafana` 로 모니터링 시각화

[spring 애플리케이션 모니터링 붙이기](https://victorious-lint-a8e.notion.site/Spring-761aa277fb084a36b4aaf4acd47faacc)
[모니터링 삽질기](https://victorious-lint-a8e.notion.site/41464b302dc34357834971531fb0a88a)
[프로메테우스 yml 설정](https://victorious-lint-a8e.notion.site/yml-e6e24faa833745328adf745fbe57f31f)

<br><br>

### 💡 참고 자료

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/73376468/224905167-4ef3d057-2912-438e-8b7a-a7017741deaf.png">

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/73376468/224905203-36eec74a-50d9-4c51-a242-45a82bc7a66a.png">

2023-03-14 11:56 UTC, ku-kim approved these changes
고생많았어요~
라이브에서 같이 봤던 Dockerfile(prometheus & grafana) 함께 첨부하면 좋을거같아요.
추가적으로 사용 방법 local 에서 실행 환경 readme에 추가면 더 좋을듯요 ㅎㅎ

2023-03-14 12:35 UTC, ku-kim requested changes
도커파일 다시 올린다면 일단 대기할게욧!

2023-03-14 12:35 UTC, ku-kim commented on src/main/resources/application.yml
이제 파일 자체에도 리뷰 남길수있네요 신기방기!

2023-03-15 15:54 UTC, donggi-lee-bit commented
> 고생많았어요~
> 라이브에서 같이 봤던 Dockerfile(prometheus & grafana) 함께 첨부하면 좋을거같아요.
> 추가적으로 사용 방법 local 에서 실행 환경 readme에 추가면 더 좋을듯요 ㅎㅎ

리뷰 감사합니다 @ku-kim !! Local 환경에서 모니터링 실행할 수 있도록 도커 파일과 리드미 추가했습니다!

2023-03-17 01:39 UTC, ku-kim approved these changes
도커 네트워크 환경을 완전 local로 변경하는 방법이 있을 거 같은데, 다음에 발견하면 공유드릴게요
고생많았어요! 💪

2023-03-18 16:16 UTC, donggi-lee-bit commented
> 

저도 더 공부해보겠습니다~~ 리뷰 감사합니닷!

2023-03-18 16:17 UTC, merged