부하테스트 자동화, 인덱스를 이용해 API 성능 개선
donggi-lee-bit/comma pull request #55
Opened 2023-04-21 09:55 UTC by donggi-lee-bit

### ❗️ 이슈 번호

Closes #52 
Closes #53 

<br><br>

### 📝 구현 내용

- `AWS EC2` 에 nGrinder Controller, agent, 테스트 서버 구축
- `GitHub Actions` 를 이용해 부하테스트 자동화 워크플로우 실행
  - `aws cli` 를 이용해 EC2 실행
  - nGrinder Rest API로 부하테스트 실행 요청
  - 부하테스트 결과 디스코드로 전송
  - `aws cli` 로 EC2 stop (자원 정리)

[부하테스트 자동화 정리](https://victorious-lint-a8e.notion.site/GitHub-Actions-aws-cli-f34561111a544f62a0dfde21fe3ba9ac)

- 인덱스를 이용해 API 성능 개선
  - 댓글(comment) 테이블의 게시글 id(comma_id) 컬럼에 인덱스 추가
    - MySQL 실행 계획으로 테이블을 풀스캔하고 있는지, 불필요하게 데이터에 얼마나 접근하는지 확인
    - 인덱스를 걸어 부하테스트 시 TPS 값이 `0.2 -> 18.1` 로 상승된 것 확인
  - 회고 게시글(Comma) 테이블에 created_at 컬럼에 인덱스 추가
    - 특정 날짜에 작성된 회고 글 조회 API 부하테스트 시 TPS 값 `4.8 -> 158.5` 로 상승된 것 확인

이전 PR에서 로컬 환경에서 부하테스트를 해보면서 배포 환경에서도 부하테스트를 해보고 싶다는 욕구가 있었습니다. 그 욕구가 부하테스트 자동화까지 가게 되었는데, 그 과정에서 많은 경험을 하였습니다.
- AWS RDS, EC2 자원 관리
- AWS CLI를 사용할 때 `aws configure` 값 설정
- 쉘 스크립트로 EC2의 public IP를 수집하여 nGrinder controller, agent, 테스트 서버를 실행하기 
- nGrinder Rest API 로 통신하여 부하테스트 실행, 결과 조회

등 기존에 GitHub Actions 로 CI/CD 외의 작업을 자동화해보니 신기하고도 재밌는 경험이었습니다.

그리고 가장 중요한 성능 개선을 해보았는데 인덱스를 걸면서도 여러 시행 착오가 있었고 아직도 알아가는 중입니다. [업무에 바로 쓰는 SQL 튜닝을 읽고 프로젝트 API 쿼리 튜닝 시행 착오 기록](https://victorious-lint-a8e.notion.site/SQL-Comma-ea373c0a0e9e4b2bbe6ef8643a08f0c6)

기한을 지키는 것도 중요한데 매번 생각한 기한보다 늦어져 아쉽네요 😅
이번에도 잘 부탁드리겠습니다 🥹

<img width="660" alt="image" src="https://user-images.githubusercontent.com/73376468/233606052-c936a420-9613-46d6-a002-3020e5e2601e.png">

2023-04-29 15:39 UTC, ku-kim requested changes
페이징의 커서가 추가되어야 할 거 같아요~

2023-05-10 07:05 UTC, donggi-lee-bit commented
@ku-kim 

안녕하세요 리뷰어님~ **페이지 메타데이터 추가**, **회고 게시글 검색 동적 쿼리로 동작하도록 변경**, **페이지 사이즈 예외처리가 아닌 방어 로직으로 동작하도록 변경** 작업 추가하였습니다.
페이지 메타데이터로는 현재 페이지, 반환되는 데이터 개수, 전체 페이지(마지막 페이지 위치로 사용)를 추가해주었습니다. 
또한 날짜, 작성자 이름, 날짜와 작성자 이름 세 가지의 게시글 검색 조건을 동적 쿼리로 동작하도록 개선하였습니다.
기존에 요청한 페이지 사이즈가 일정 크기 이상(게시글 : 100개, 댓글 : 10개)일 경우 예외를 반환하도록 하였는데 페이지 사이즈로 예외를 반환하는 로직의 흐름이 이상하다고 판단하여 정해놓은(게시글 : 100개, 댓글 : 10개) 최대 크기로 데이터를 반환하도록 변경하였습니다.

2023-05-12 12:23 UTC, ku-kim approved these changes
대면 리뷰 check,
Pageable global 옵션 설정과 상수 처리, Sort 유효성 검증 정도 추가하시면 좋을 거 같습니다~

2023-05-12 18:50 UTC, donggi-lee-bit commented
@ku-kim 

피드백 받은 작업 추가하여 Merge 하겠습니다!
- 데이터베이스 실행 파일 추가
- 페이지 전역 설정
- 서비스 로직에서 페이지 방어 로직을 ArgumentResolver 에서 처리하도록 변경
- 페이지 정렬 방어 로직 Interceptor 에서 처리하도록 개발


다음 PR 에 해당 작업 상세 내용도 포함시키도록 하겠습니다 😆

2023-05-12 18:50 UTC, merged